language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - python -m pip install . --ignore-installed --no-deps

script:
  - python -m unittest importnb/__init__.py